import React from "react";
import { Link } from "react-router-dom";
import { Image } from "@/components/ui/image";
import SectionTitle from "@/components/SectionTitle";
const link = "mt-7 inline-flex rounded-full bg-[#1B5E20] px-6 py-4 text-sm font-bold text-white";
export default function HomeSections() { return <>
<section className="px-5 py-20 lg:px-8"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-2"><Image src="https://media.base44.com/images/public/6a75f1f68617f8a7b5abfa7c/62003a3c4_WhatsAppImage2026-08-04at14165230.jpg" alt="Children playing table tennis at the centre" className="h-[430px] w-full rounded-[2rem]"/><div><SectionTitle label="WHO WE ARE" title="Community-rooted care that opens pathways forward." text="We support children, youth, individuals and families through social support, education, group interventions, community development and awareness programmes."/><Link className={link} to="/about">ABOUT OUR CENTRE</Link></div></div></section>
<section className="bg-[#F7F7F3] px-5 py-20 lg:px-8"><div className="mx-auto max-w-7xl"><SectionTitle label="OUR PROGRAMMES" title="Seven programmes. One connected community."/><div className="mt-10 grid gap-5 md:grid-cols-3">{[["Early care","A nurturing foundation for children aged 1–5."],["Youth development","Mentorship, identity, life skills and academic growth."],["Family & community","Casework, nutrition, awareness and practical support."]].map(x=><div className="rounded-3xl bg-white p-7" key={x[0]}><h3 className="font-heading text-2xl text-[#1B5E20]">{x[0]}</h3><p className="mt-3 leading-7 text-black/60">{x[1]}</p></div>)}</div><Link className={link} to="/programmes">VIEW ALL PROGRAMMES</Link></div></section>
<section className="bg-[#1B5E20] px-5 py-20 lg:px-8"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2"><SectionTitle light label="HOW WE WORK" title="Support shaped around real lives." text="Casework, group work and community work connect individual care with collective strength."/><div className="grid gap-4">{["01  CASEWORK","02  GROUP WORK","03  COMMUNITY WORK"].map(x=><div className="rounded-2xl border border-white/20 p-6 text-lg font-bold text-white" key={x}>{x}</div>)}<Link className="mt-3 text-sm font-bold text-[#FFB300]" to="/how-we-work">EXPLORE OUR APPROACH →</Link></div></div></section>
</>; }